### ISSUE TITLE
`flood_sleep_threshold` unused?

### ISSUE THREAD

**Issue by mkpankov** [Lonami/grammers#113]
I'm seeing `RpcError { name: "FLOOD_WAIT", value: Some(17) }`. I have `flood_sleep_threshold: Some(60),` in my params.
I've cloned entire `grammers` repo and only 3 mentions of this field are found
![image](https://user-images.githubusercontent.com/393741/168245692-8c849ec7-694b-47b6-abd3-6f804c681e73.png)
none of which actually read that value or pass it down.

Am I missing something or this field is a stub for the future?

**Comment by Lonami** [comment]
This field is a stub for the future.

**Comment by mkpankov** [comment]
Ok, thanks for explanation

**Comment by Lonami** [comment]
We can keep this open to track its implementation.

If you (or someone else) is interested in implementing this, it should be as simple as modifying the `invoke` method:

https://github.com/Lonami/grammers/blob/3ed47232c01dc3c05426cc3c346e7deb1dadc002/lib/grammers-client/src/client/net.rs#L221

to detect this error and sleep automatically before retrying. Telethon is slightly more advanced and keeps a cache of "floodwaited requests" to avoid sending them entirely if we know they would floodwait, but for an initial implementation, it is not necessary.

**Comment by mkpankov** [comment]
I saw some implementation in git history. Why it was removed?

**Comment by Lonami** [comment]
Might have been removed unintentionally on accident, or intentionally temporarily during refactoring. I can't really remember. But the idea definitely is for it to be implemented.
