### ISSUE TITLE
full iter_messages example

### ISSUE THREAD

**Issue by olifur** [Lonami/grammers#115]
Hello everyone,

I am struggling to get a simple program running which prints the last message(s) of a group chat.

I am coming from a telethon background and know that iter_messages is the correct API method.

Here is an example code https://docs.rs/grammers-client/0.3.0/grammers_client/client/client/struct.Client.html#method.iter_messages

But as I am very new to RUST at all I have problems to get this demo working.

How is the chat method parameter used?

Its of type https://docs.rs/grammers-client/0.3.0/grammers_client/types/chat/enum.Chat.html. But I cannot get tit to work when I define it.

Could you please provide me with a full working iter_messages example?

Best,
Oliver

**Comment by Lonami** [comment]
Hi, I'm glad you're giving the library a try, but I'd appreciate if we kept the issues sections for actual issues in the library. You can ask your question in https://t.me/gramme_rs where there's plenty of people who can help. Thanks!
