### ISSUE TITLE
Consider alternative serialization mechanisms

### ISSUE THREAD

**Issue by Lonami** [Lonami/grammers#12]
Currently, serialization of types is fallible:
https://github.com/Lonami/grammers/blob/ab05f96e3a043447633c3841e93434c5d9d62fb2/lib/grammers-tl-types/src/serializable.rs#L16

This is because we use the `Write` trait, which can fail with `io::Error`. But we know our data is well-formed and serialization can never fail. We should look into infallible alternatives.

This was inspired by [amos - Parsing and serializing ICMP packets with cookie-factory](https://fasterthanli.me/blog/2019/making-our-own-ping-12/), where they use [`cookie-factory`](https://crates.io/crates/cookie-factory) for their needs. It has no dependencies, so it may be worth to look at.

**Comment by JuanPotato** [comment]
I mean if you're only using vec\<u8\> then why even use the write trait

**Comment by Lonami** [comment]
Because `Write` is an abstraction over buffers I can write to, and tying it to the very specific `Vec<u8>` seemed less than ideal. For example, it could work with a cursor over a slice if I wanted.

**Comment by Lonami** [comment]
As of https://github.com/Lonami/grammers/commit/67f09912e1b8735e5a2202b5c17c8be6097240dd, (de)serialization occurs always over `Vec<u8>` (fully in-memory), so we can get rid of serialization failure (but deserialization failure remains, because at any point we may find a constructor identifier we don't recognise, or we may run out of bytes).

Types are normally small, so that doing everything in-memory should not be an issue (and even if they could be streamed, they would likely end up in outgoing buffers regardless). I think it's also nice, since IO and work on serde is fully separated.

Closing.
