### ISSUE TITLE
Update offset on fetching participant of channel

### ISSUE THREAD

**Issue by Misha-Br** [Lonami/grammers#124]
https://github.com/Lonami/grammers/blob/c159fb086224342a4a45f719874cc675a0db5e46/lib/grammers-client/src/client/chats.rs#L136
You need to add:
`iter.request.offset = iter.fetched as i32;`

**Comment by Lonami** [comment]
This is done later:

https://github.com/Lonami/grammers/blob/c159fb086224342a4a45f719874cc675a0db5e46/lib/grammers-client/src/client/chats.rs#L144-L146

Does it not work as-is?

**Comment by Misha-Br** [comment]
Error on https://github.com/Lonami/grammers/blob/c159fb086224342a4a45f719874cc675a0db5e46/lib/grammers-client/src/client/chats.rs#L137
Because of offset is 0, it requests participants from begin.
You can to reproduce this bug with with channel where more on 200 users

**Comment by Lonami** [comment]
`fetched` starts at 0.

https://github.com/Lonami/grammers/blob/c159fb086224342a4a45f719874cc675a0db5e46/lib/grammers-client/src/types/iter_buffer.rs#L32

When `fill_buffer` is called, it will start with offset 0. Then if it's not the last chunk, the offset will be increased by the amount of participants it got. When `fill_buffer` is called again, it will remember that offset.

https://github.com/Lonami/grammers/blob/c159fb086224342a4a45f719874cc675a0db5e46/lib/grammers-client/src/client/chats.rs#L133-L159

Sorry but I cannot find the issue.

**Comment by Misha-Br** [comment]
https://github.com/Lonami/grammers/blob/c159fb086224342a4a45f719874cc675a0db5e46/lib/grammers-client/src/client/chats.rs#L137 
You call "invoke" method and put the "iter.request" as argument. But you need to update the "offset" field before. Else it will request first MAX_PARTICIPANT_LIMIT items always.

**Comment by Lonami** [comment]
The problem was that the check to update the offset was in the wrong place. This has been fixed by the above commit. Thanks.
