### ISSUE TITLE
drop(message_box) is called in the next_update method

### ISSUE THREAD

**Issue by tingfeng-key** [Lonami/grammers#125]
I'm planning to write a long running update command line tool that stores some information in a database each time an update is fetched. After running for about 2-3 hours, it (cli) will stop automatically (the reason I found after debugging is that `drop(message_box)` is called), I am very confused. I see that the `get_difference` and `get_channel_difference` methods are called in the `next_update` method. Sometimes I see a print with Log:`stepped` in the cli.
I would like to ask for knowledge about this.
1. Under what circumstances will the `drop(message_box)` method be triggered?
2. What is the impact of not calling `drop(message_box)` if `drop(message_box)` is required?

![image](https://user-images.githubusercontent.com/13976521/182287695-e4f796a4-4d4d-4922-aacf-1e8e4823dfe0.png)
info and warn are what I print.

**Comment by Lonami** [comment]
> 1. Under what circumstances will the `drop(message_box)` method be triggered?

Just to be clear, the `message_box` itself is not dropped, only the lock around it (the naming may be confusing without context). The lock must be held for as little as possible because other parts may try to access it, and it's not re-entrant.

> What is the impact of not calling `drop(message_box)` if `drop(message_box)` is required?

Some other part of the code may try acquiring the lock before the old one was acquired, leading to a deadlock.

**Comment by Lonami** [comment]
Unfortunately the log info you posted seems normal (I can't spot any deadlocks). Because it runs for considerably longer than 15 minutes (which is when the automatic, forced get difference calls are made if there have been no updates), it might be a different issue with locks. Not sure.

**Comment by tingfeng-key** [comment]
Thank you for solving the puzzle. At present, this problem still exists. I must guard it to deal with it

**Comment by Lonami** [comment]
Has the problem been fixed? If not I would prefer to keep the issue open.

**Comment by tingfeng-key** [comment]
I have an issue that may be related to this issue. After I run for a while. get:
`read error, IO failed: read 0 bytes`
So I found the lib.rs file of `grammers-mtsender` zh oh that, and saw the `on_net_read method`
```rust
fn on_net_read(&mut self, n: usize) -> Result<Vec<tl::enums::Updates>, ReadError> {
        if n == 0 {
            return Err(ReadError::Io(io::Error::new(
                io::ErrorKind::ConnectionReset,
                "read 0 bytes",
            )));
        }

        trace!("read {} bytes from the network", n);
```
I don't know what happens when n is equal to 0. Can this loop be skipped here instead of error?

**Comment by Lonami** [comment]
When a network `read` returns 0 bytes, this generally indicates the connection has been closed. This is why the check exists and why that particular error is raised.

When the library disconnects, it should automatically reconnect. There was someone interested in implemented this, but I don't know how far they've gotten.

**Comment by tingfeng-key** [comment]
Well, I looked at the source code of the network connection part, but for my current ability, I still can't handle this problem. Hope someone can handle it

**Comment by tingfeng-key** [comment]
In my last actual running test (running for nearly four hours, no network exceptions), the program was not found to actively stop. I will do a longer run test

**Comment by tingfeng-key** [comment]
It's been 16 hours since it started running and everything is working fine, no downtime, it's time for me to shut it down. Thank u

**Comment by tingfeng-key** [comment]
I think it should be related to these two commits， [9f773a9](https://github.com/Lonami/grammers/commit/9f773a971a4a2ec1f207b76bfc58942e97a99ea5)，[42b5637](https://github.com/Lonami/grammers/commit/42b5637c023cd04469e66b2694b44841a7bc44a5)
