### ISSUE TITLE
Derive Clone to Config and InitParams

### ISSUE THREAD

**Issue by jonnyfer** [Lonami/grammers#133]
There are some situations in which someone might need to use `grammers_client::client::client::Client::Connect` multiple times (or at least I do), for example, when using multiple sessions/clients, or when changing the connection's datacenter (via an edit of config.session).
Deriving `Clone` for `grammers_client::client::client::Config` might be helpful in this regard (`Connect` takes a `Config`), allowing those who want, to write something like:
```
let config1 = Config {
    *fields,
};
let mut client1 = Client::connect(config1.clone()).await?;

let config2 = Config {
    session: Session::load_file_or_create("file.session")?,
    ..config1
};
let mut client2 = Client::connect(config2).await?;
```
instead of:
```
let config1 = Config {
    *fields,
};
let mut client1 = Client::connect(config1).await?;

let config2 = Config {
    *fields,
};
let mut client2 = Client::connect(config2).await?;
```

The same applies to `grammers_client::client::client::InitParams`, that would benefit from deriving `Clone` in a similar way (other than being needed to derive `Clone` on `Client`).

**Comment by Lonami** [comment]
My main concern here is that the config includes the `Session`, which is not intended to be used by multiple clients at once. Misbehaviour is likely to occur if the same session is reused. However, the `InitParams` can definitely derive `Clone`. Would that alleviate the problem in any meaningful way?

I'd recommend creating a closure which you can call over and over to create new distinct `Config`, or even a standalone `fn give_me_config() -> Config`.

**Comment by jonnyfer** [comment]
What you're saying is of course true, and I agree with you to a certain degree. But this would work without any problems if done correctly.
In any case, there's no current way to prevent a user from writing this and running in misbehaviour:
```
let session1 = Session::load_file_or_create("file.session")?;
let config1 = Config {
    session: session1,
    *fields,
};
let mut client1 = Client::connect(config1).await?;

let config2 = Config {
    session: session1,
    *fields,
};
let mut client2 = Client::connect(config2).await?;
```

Anyway, if deriving `Clone` to `Config` truly concerns you, it would still be nice to derive `Clone` to `InitParams`.
I'll follow your suggestion and I'll write a specific function to generate the config.

**Comment by Lonami** [comment]
It's true the library can't fully mitigate misuse (well, without global shenanigans), but I still feel more comfortable not having `Clone`. A `.clone()` call is far easier to type than the full `Session::load_file_or_create`. We can add `Clone` to `InitParams`. Feel free to send a PR for that.

If the function to generate config turns out to be too annoying to write for whatever reason we could argue about that a bit more and maybe I'd change my mind, but we'd have to document against the potential misuse (and documentation is harder to enforce).

**Comment by Lonami** [comment]
Alright, thanks for the PR and understanding my POV.
