### ISSUE TITLE
Why Client implementation methods marked as &mut self ?

### ISSUE THREAD

**Issue by Ridtt** [Lonami/grammers#136]
For example pub async fn is_authorized(&mut self)
Client is just a wrapper around clonable struct with all interior mutability fields, there is nothing you can have mutable access in Client. 
I had two hours figurning out what is going on here and trying to make decision for best way to share Client in my application.
If you see struct methods taking mutable self reference you assuming its not thread safe (dont you?), but thats no case for Client, its totally safe by design. What you want to approach by making them &mut self?

**Comment by Lonami** [comment]
Might be from the time where `Client` and `ClientHandle` were separate things (there's no such separation in the current git version). Please be welcome to send a pull request removing the `&mut` need from client methods.

I don't think there's really any reason to have some methods require a mutable reference anymore. As you point out it's just a weird annoyance.

**Comment by Lonami** [comment]
Perhaps it was semantics (e.g. if you mark a message as read, it makes sense that the message was mutated so the method would require mutable access). But it's kind of an absurd artificial limitation.
