### ISSUE TITLE
Comparing RpcErrors is annoying

### ISSUE THREAD

**Issue by Lonami** [Lonami/grammers#15]
Probably enough to `impl PartialEq for &'static str` in `RpcError` to make it a lot nicer to use. Not sure if this will work in `match` but it will at least work in `elif` chains.

**Comment by Lonami** [comment]
Currently things look like this (note the `starts_with` and `==`):

https://github.com/Lonami/grammers/blob/67f09912e1b8735e5a2202b5c17c8be6097240dd/lib/grammers-client/src/client/auth.rs#L286-L315

It isn't *too* bad, but I still wonder if it could be improved.

Unfortunately, things like:

```rust
Err(InvocationError::Rpc(RpcError { name: "SESSION_PASSWORD_NEEDED", .. }))
```

do not work, because `name` is an owned `String`. Now, we *could* get that pattern matching to work:

```rust
struct RpcError {
    buffer: Vec<u8>,
    pub name: &'static str,
}

impl RpcError {
    fn new(err: String) -> Self {
        let buffer = err.into_bytes();
        let name = unsafe { std::mem::transmute(buffer.as_slice()) }; // transmute lifetime into static
        
        Self {
            buffer,
            name,
        }
    }
}

fn main() {
    let err = RpcError::new("FOO_BAR".to_string());
    match err {
        RpcError { name: "FOO_BAR", .. } => println!("got foo bar"),
        _ => {},
    }
}

```

…but this is wildly unsafe (if the buffer is dropped early and the name matched against after, that would be reading from freed memory and easily violate the UTF-8 invariant).

Unfortunately, it seems macros cannot have pattern guards, so this does not work either:

```rust
macro_rules! rpc_err {
    ($err:ident) => {
        Err(grammers_mtsender::InvocationError::Rpc(RpcError { name, .. })) if name == "$ident"
    };
}
```

(although it would solve most of our issues).

Should we aim for a better design, or is it good enough for the use people will make out of it? (I'm not sure how often you'll be matching on specific errors.)

**Comment by Selicre** [comment]
I usually solve this with an inherent method like `.is` or `.eq` that allows you to compare with `str` without having to use any other accessor:

```rust
let err = RpcError::new("FOO_BAR".to_string());
if err.is("FOO_BAR") {
    do_thing();
}
```

This doesn't let you use mattern matching, but it's good enough.

**Comment by Lonami** [comment]
Comparisons to that suggestion:

```rust

Err(InvocationError::Rpc(RpcError { name, .. })) if name == "SESSION_PASSWORD_NEEDED" => {}

Err(InvocationError::Rpc(rpc)) if rpc.name == "SESSION_PASSWORD_NEEDED" => {}

Err(InvocationError::Rpc(rpc)) if rpc.is("SESSION_PASSWORD_NEEDED") => {}

Err(err) if err.is("SESSION_PASSWORD_NEEDED") => {}
```

**Comment by Lonami** [comment]
The leak approach from https://github.com/Lonami/grammers/issues/15#issuecomment-841637824 can be made safer by leaking the `String` into a `str`, and `impl Drop` on the error (where the `String` is re-constructed, and correctly dropped/freed). However, it would still introduce one `unsafe` block (and the library is currently `unsafe`-free which is nice).

**Comment by Lonami** [comment]
Will likely go with the `.is` approach on the `InvocationError` itself, and support a trailing (and leading?) asterisk (to switch to `starts_with`).
