### ISSUE TITLE
HISTORY_GET_FAILED caused by updates.getChannelDifference

### ISSUE THREAD

**Issue by tingfeng-key** [Lonami/grammers#150]
When I run it for a period of time (the last time was 10 minutes), it has an error:
```rust
Error: request error: rpc error 500: HISTORY_GET_FAILED caused by updates.getChannelDifference
```

**Comment by Lonami** [comment]
The library needs to handle all 500 errors in this `match`:

https://github.com/Lonami/grammers/blob/96f61a16b4c4ba5e33175fbaafae061dcbd4af25/lib/grammers-client/src/client/updates.rs#L80-L82

The handling is essentially the same as that of `PERSISTENT_TIMESTAMP_OUTDATED`, so we can simply update the condition to enter that arm when either this or the error 500 occurs.

You can refer to [Telethon's implementation](https://github.com/LonamiWebs/Telethon/blob/db29e9b7efb204fbe56fe8d59ccc4d55ceddc165/telethon/client/updates.py#L308) as well if you need more context.

Please feel welcome to send a pull request (it should be simple, just enter the `Err` branch if the error is 500 too).
