### ISSUE TITLE
Telethon - Add Inline Buttons For Message

### ISSUE THREAD

**Issue by 7M1T** [Lonami/grammers#16]
Hi !

I tried to add inline button to my script, I logged as a bot and i'm trying to send two button - The first option is to share any link to website and the second is to share the specif group i'm posting in, something like this format of message - picture/s, any text and the inline buttons

I added the following code part  but the output is only the text ..

@client.on(events.CallbackQuery)
async def callback(event):

client.send_message(output_channel_names[i], 'A single button, with "clk1" as data',
                    buttons=Button.inline('Click me', b'clk1'))

I tried some other option like this but the output stays the same ..

client.send_message(output_channel_names[i], 'out', buttons=Button.inline('Click', b'clk1'))
client.send_file(output_channel_names[i], 'out', buttons=Button.inline('Click here to', b'clk2'))
client.send_message(output_channel_names[i], 'out', buttons=Button.button('Click here to share', 'https://lonamiwebs.github.io'))

client.send_message(output_channel_names[i], 'Pick one from this grid', buttons=[
    [Button.inline('Left','HEY'), Button.inline('Right')],
    [Button.url('Check this site!', 'https://lonamiwebs.github.io')]
])
Can you please help me here ?

much appreciation !

@Lonami

**Comment by 7M1T** [comment]
Hi !

I tried to add inline button to my script, I logged as a bot and i'm trying to send two button - The first option is to share any link to website and the second is to share the specif group i'm posting in, something like this format of message - picture/s, any text and the inline buttons

I added the following code part  but the output is only the text ..

@client.on(events.CallbackQuery)
async def callback(event):

client.send_message(output_channel_names[i], 'A single button, with "clk1" as data',
                    buttons=Button.inline('Click me', b'clk1'))

I tried some other option like this but the output stays the same ..

client.send_message(output_channel_names[i], 'out', buttons=Button.inline('Click', b'clk1'))
client.send_file(output_channel_names[i], 'out', buttons=Button.inline('Click here to', b'clk2'))
client.send_message(output_channel_names[i], 'out', buttons=Button.button('Click here to share', 'https://lonamiwebs.github.io'))

client.send_message(output_channel_names[i], 'Pick one from this grid', buttons=[
    [Button.inline('Left','HEY'), Button.inline('Right')],
    [Button.url('Check this site!', 'https://lonamiwebs.github.io')]
])
Can you please help me here ?

much appreciation !

@Lonami

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
