### ISSUE TITLE
AUTH_KEY_DUPLICATED

### ISSUE THREAD

**Issue by tingfeng-key** [Lonami/grammers#170]
tip:
`rpc error 406: AUTH_KEY_DUPLICATED caused by invokeWithLayer`

I seem to be why this is happening. I can be sure that my account is not lost. When this problem occurs, I did not operate the telegram account, only one cli is running

I did some research on how to re-use the session file when recreating it. I'm curious as to why this is happening, and then how to fix it.

My operating environment: running in windows10, using `socks5 proxy`, `socks5 proxy` sometimes has a high delay problem, for this case, I set up the operation of recreating the` client instance`, that is, if this error message is returned, it will log in again, If the login is successful, delete the old client instance (`drop`) and use the new client operation

[Telethon #777](https://github.com/LonamiWebs/Telethon/issues/777)

[tdlib AUTH_KEY_DUPLICATED](https://github.com/tdlib/td/issues/353)

[Telethon #754](https://github.com/LonamiWebs/Telethon/issues/754)

[webogram #1674](https://github.com/zhukov/webogram/issues/1674)

**Comment by Lonami** [comment]
This error is likely outside our control https://github.com/LonamiWebs/Telethon/blob/v1.27.0/telethon_generator/data/errors.csv#L18. That's all I know.
