### ISSUE TITLE
Answer a reply_markup from a BOT message

### ISSUE THREAD

**Issue by felipepimsil** [Lonami/grammers#191]
Is there a way to answer a reply_markup? I connected with my user and wanted to answer some buttons from a BOT message, but I didn't find some method.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).

**Comment by RuofengX** [comment]
Client currently don't have a reply markup method.

**Comment by Lonami** [comment]
When I posted my comment, I thought I was in the Telethon repository.

Either way, since the issue was posted, it's now possible:
https://github.com/Lonami/grammers/blob/8997a2dadc64b9ee7ee4d03b2f6eaba15d44f00c/lib/grammers-client/src/types/input_message.rs#L81

**Comment by RuofengX** [comment]
> When I posted my comment, I thought I was in the Telethon repository.
> 
> Either way, since the issue was posted, it's now possible:
> https://github.com/Lonami/grammers/blob/8997a2dadc64b9ee7ee4d03b2f6eaba15d44f00c/lib/grammers-client/src/types/input_message.rs#L81

I think there is a mistake.  

reply_markup function send a button in message.   
We still can't press the button that peer send. 


For example, I am talking with a bot, received a message with button on it, and want my client to press a button behind the msg sent by bot.

**Comment by Lonami** [comment]
You can `client.invoke` that request, but you're right a friendly API is missing.

Ideally the `Message` custom type would have a `.buttons()` that can be `.click()`ed.
