### ISSUE TITLE
Use logging

### ISSUE THREAD

**Issue by Lonami** [Lonami/grammers#2]
Currently, it's pretty hard to trace errors when they happen. It would be helpful to use a wide-spread logging library and insert calls around the code.

**Comment by swarnimarun** [comment]
Suggestions:
- [ ] slog-rs (rich but heavy)
- [ ] log (logging facade) (very minimal)
- [ ] dedicated lightweight implementation similar or on top off `log`

**Comment by Lonami** [comment]
[`slog-rs`](https://github.com/slog-rs/slog) might be a bit overkill, and although it could come in helpful (ideally we will have several tasks running in parallel handling network), I would prefer to keep the core libraries free of bloat.

I like the idea of using [`log`](https://crates.io/crates/log), it seems simple and small enough, and end-users are the ones deciding on the final logging implementation.

Not sure if rolling our own logging is a good idea: `log` already exists, and has been tested extensively, with hundreds of projects using it.

**Comment by swarnimarun** [comment]
> [`slog-rs`](https://github.com/slog-rs/slog) might be a bit overkill, and although it could come in helpful (ideally we will have several tasks running in parallel handling network), I would prefer to keep the core libraries free of bloat.
> 
> I like the idea of using [`log`](https://crates.io/crates/log), it seems simple and small enough, and end-users are the ones deciding on the final logging implementation.
> 
> Not sure if rolling our own logging is a good idea: `log` already exists, and has been tested extensively, with hundreds of projects using it.

I absolutely agree, if we just want grammers to be a reusable library it should be quite sufficient.

**Comment by sigod** [comment]
I too vote for `log`. There's no real reason to keep anything more complicated inside of the library.

**Comment by Lonami** [comment]
I think logging is in a good state (both the sender and update handling make a decent use of logging). We can still add more logging calls as we see fit, but I think this issue has served its purpose, so closing.
