### ISSUE TITLE
Lost updates sometime

### ISSUE THREAD

**Issue by AkkermanD** [Lonami/grammers#204]
Hi. Thanks for the great library! :bow:  I'm trying to build TG -> Mastodon bridge with it and learn myself some rust.

Facing an issue with lost TG updates from chats however. The app is running fine and receives updates from TG, but sometimes (once in a few days) the update is not received by app at all. No errors, it feels like update was not sent by TG side at all.
Could it be because I'm using my own TG account that is logged at the same time on my phone via official TG app, maybe? Does TG retry delivery to all connected devices?

I'm using master branch of the library from Sep 29, 2023 (`5cee34a`)

**Comment by Lonami** [comment]
I would need to see if the logs mention "gaps" and the library attempted to recover. Never checked how it behaves if Telegram delays an update which is deleted before it's delivered, though.

**Comment by AkkermanD** [comment]
Will gather the logs, may take some time, but I'll get back with them :)

For the deleted updated - should not be the case, as I can see it via the official app.

**Comment by AkkermanD** [comment]
Can't reproduce the issue for some reason :) Maybe I was doing something wrong related to the edited messages :shrug:
I'd close the issue for now, and will reopen with logs if I'll face it again. Thanks for the library!

**Comment by AkkermanD** [comment]
And this happened again the same day I closed the issue :)
So here's the TG message: https://t.me/Velo_kyiv_rides/1873
Posted: 2023-11-17 20:55:18 UTC, logs: https://pastebin.com/fRWgVrk3
Edited: 2023-11-17 21:11:26 UTC, logs: https://pastebin.com/DKnNdthK

Looks like message was never delivered to the app. I'm using an account that is simultaneously logged in on my phone and via the bot application. Phone got the message, but application did not. Please let me know if I can provide any other information.

**Comment by Lonami** [comment]
> I'm using master branch of the library from Sep 29, 2023 (5cee34a)

Might be worth to try on a newer version. It may have been fixed.

**Comment by taimast** [comment]
> > I'm using master branch of the library from Sep 29, 2023 ([5cee34a](https://github.com/Lonami/grammers/commit/5cee34a68aba1fd2ac621ef84907065e5954e7f6))
> 
> Might be worth to try on a newer version. It may have been fixed.
> 
> Otherwise, if you can describe an scenario with steps I should follow to reproduce the issue, I could try myself (like, "create a channel, do this, then that, and the bug should happen").

This behavior appeared to me too. It doesn't always appear.  Put a handler that immediately responds with any message and create a new session. Start sending a few messages and he misses some.

**Comment by taimast** [comment]
> > > I'm using master branch of the library from Sep 29, 2023 ([5cee34a](https://github.com/Lonami/grammers/commit/5cee34a68aba1fd2ac621ef84907065e5954e7f6))
> > 
> > 
> > Might be worth to try on a newer version. It may have been fixed.
> > Otherwise, if you can describe an scenario with steps I should follow to reproduce the issue, I could try myself (like, "create a channel, do this, then that, and the bug should happen").
> 
> This behavior appeared to me too. It doesn't always appear. Put a handler that immediately responds with any message and create a new session. Start sending a few messages and he misses some. I guess this behavior may occur at the beginning for new sessions.

It can also occur, for example, if you leave a running session alone without sending any messages, and it will skip the first few messages

**Comment by rs-pro0** [comment]
I think this is fixed by #229
