### ISSUE TITLE
Reconnection policies are not in the released crate

### ISSUE THREAD

**Issue by dredozubov** [Lonami/grammers#205]
I was trying to recreate a `reconnection` example, and I realized `ReconnectionPolicy` was added later than 0.4.0 was released as a crate. Do you think you can release a newer version with upstream changes?

**Comment by Lonami** [comment]
Will try to find some time to submit a new release. However, I'd still suggest using the `git` version:

```toml
grammers-client = { git = "https://github.com/Lonami/grammers" }
```

Maybe I'll update the crates.io README to include this as well.

**Comment by Lonami** [comment]
Should be out.

**Comment by dredozubov** [comment]
Thank you, @Lonami. I was using the git version in the meantime, great to see it release, so I'm going to switch to a crate version now.
