### ISSUE TITLE
About the `0.5.0` version

### ISSUE THREAD

**Issue by TheAwiteb** [Lonami/grammers#209]
I noticed that there is version number 0.5.0 on crates.io for [`grammers-client`](https://crates.io/crates/grammers-client) and it is not [here in the repository](https://github.com/Lonami/grammers/blob/47cb50e35c969998a41dc32f2fe126a7d1ffcdb5/lib/grammers-client/Cargo.toml#L3), why?

**Comment by Lonami** [comment]
Forgot to push - the commits are now in (https://github.com/Lonami/grammers/commit/b583c89f06acd6da30eb13b22da305b091c3d8b2). Thanks.
