### ISSUE TITLE
[BUG] Markdown and Html parse insertion left behind

### ISSUE THREAD

**Issue by velaton618** [Lonami/grammers#223]
The text

<img width="327" alt="image" src="https://github.com/Lonami/grammers/assets/98014243/c86e4ce0-b7f6-4890-b319-b23f97cdef3b">

🆕 Kyrgyzstani som and new payment methods in 💠 P2P Market.

Kyrgyzstani som and the following payment methods for this currency are already available in P2P Market: MBank, Doscredobank, Bakai Bank, FINCA Bank, Optima Bank, DemirBank, MegaPay, О!Money.

To buy or sell coins using this new currency, go to P2P Market, tap “Payment and Currencies” and choose “KGS” in the list. 

We've also added new payment methods for the existing currencies:
• UralSib, UniCredit Bank, Levoberezhny Bank, GenBank, Ak Bars Bank, LAVA for RUB;
• Forte Bank and Jusan for KZT.

To configure your payment methods, go to P2P → “Payment and Currencies” → “Payment Methods”.

throws an error

![telegram-cloud-document-2-5220067332746923249](https://github.com/Lonami/grammers/assets/98014243/81543f5d-0feb-484a-a30f-74b5c408a518)

**Comment by Lonami** [comment]
https://github.com/Lonami/grammers/commit/0108ec3976fd4b8e45c83fdb32bd20bc2e6b390a
