### ISSUE TITLE
Received an update referencing an unknown peer, treating as gap

### ISSUE THREAD

**Issue by velaton618** [Lonami/grammers#226]
This log is **sometimes** received from a channel that is in user's dialogs, and user has subscribed to the channel.

The log:

```log
10:19:59 [INFO] received an update referencing an unknown peer, treating as gap
```

The channel: @news_crypto

The code that doesn't work correctly:

lib > grammers_session > src > message_box > mod.rs:363

**Comment by Lonami** [comment]
Closing in favor of the more-recent #240.
