### ISSUE TITLE
ClientHandle, EntitySet and UpdateIter not included in grammers_client.

### ISSUE THREAD

**Issue by ThijmenMaus** [Lonami/grammers#25]
I'm trying to reproduce the [`echo.rs`](https://github.com/Lonami/grammers/blob/master/lib/grammers-client/examples/echo.rs) example, and when I import it I get the following issue:
https://imgur.com/a/nIB4eMf

I've cleaned and rebuilt the project, but this didn't help with the issue..

This is my cargo.toml:
```
[package]
name = "foo"
version = "0.1.0"
authors = ["bar <bar@foo.baz>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
grammers = "0.1.0"
grammers-client = "0.2.0"
grammers-crypto = "0.2.0"
grammers-mtproto = "0.2.0"
grammers-mtsender = "0.2.0"
grammers-session = "0.2.0"
grammers-tl-gen = "0.2.0"
grammers-tl-parser = "1.0.0"
grammers-tl-types = "0.2.0"
tokio = { version = "0.3", features = ["full"] }
```

Could you help me resolve this?

**Comment by Lonami** [comment]
What to expose from the `-client` so that no other libraries are needed is a work in progress until the public API is fleshed out (we chatted in Telegram but just for the sake of recording this in the issue too).

**Comment by Lonami** [comment]
As of 0.3, `ClientHandle` is gone, I removed `UpdateIter` recently, and the `EntitySet` will be handled transparently by the library (so it won't be exposed to end users at all).
