### ISSUE TITLE
Get file download progress

### ISSUE THREAD

**Issue by rohitsangwan01** [Lonami/grammers#259]
Hey great work, can we get File download Progress somehow ?
and FloodWait handled internally or do we have to handle that manually ?

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
