### ISSUE TITLE
Any traffic transmitted should be encrypted with a temp auth key

### ISSUE THREAD

**Issue by habnabit** [Lonami/grammers#28]
Using an ephemeral temp auth key for all traffic instead of the permanent auth key means that traffic can't be captured and decrypted after the fact if the auth key is later leaked or stolen. This is a very common mitigation used in modern TLS suites. (TLS 1.3 only supports ephemeral key exchange groups.)

**Comment by Lonami** [comment]
I'm personally not interested in this and I'd like to prune issues, so I'll be preemptively closing this. But still happy to merge such a PR.

**Comment by habnabit** [comment]
dang i opened this four years ago? aight i'll work on it sometime soon since i'm actually using the library now as of like last week.

**Comment by Lonami** [comment]
We can of course still talk about it and I'm happy to help / guide through the library, perhaps in the gramme_rs group in Telegram, if you prefer.
