### ISSUE TITLE
How to receive the latest messages?

### ISSUE THREAD

**Issue by youngbloood** [Lonami/grammers#280]
How to get the latest messages in Rust?

like the `telethon`'s `client.add_event_handler` function. this is the [link](https://github.com/LonamiWebs/Telethon/blob/3f589b287deca7b3aa9abc5136bec2ec26a4e7ae/telethon/client/updates.py#L130)

Then use add_event_handler, will receive the latest message in Group or Channels or Users.

**Comment by Lonami** [comment]
Hi, this is not an issue with the library but rather a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [the @gramme_rs group](https://t.me/gramme_rs).
