### ISSUE TITLE
Accept invite should return a Chat not Updates, just like join_chat do.

### ISSUE THREAD

**Issue by RuofengX** [Lonami/grammers#281]
https://github.com/Lonami/grammers/blob/8997a2dadc64b9ee7ee4d03b2f6eaba15d44f00c/lib/grammers-client/src/client/chats.rs#L785-L795
https://github.com/Lonami/grammers/blob/8997a2dadc64b9ee7ee4d03b2f6eaba15d44f00c/lib/grammers-client/src/client/chats.rs#L810-L840

**Comment by Lonami** [comment]
This probably wasn't done because there's no ID in `accept_invite_link` to find what `Chat` to `return`.

But, assuming there is a single one, returning the first one should work too.
