### ISSUE TITLE
Client.download_media returns before file has downloaded

### ISSUE THREAD

**Issue by fubz** [Lonami/grammers#288]
How do I wait for client.download_media to finish before proceeding with my code?  I noticed that client.download_media spawns a task and my app will continue to proceed which results in an end of stream error as my application opens a file that most of the time has not been written to yet.

Is there a way to download a file and return once complete? 

It's possible to recreate with the example that downloads media, simply load the media and most, but not all, due to the async nature. The file will not load.

**Comment by Lonami** [comment]
> How do I wait for client.download_media to finish before proceeding with my code?

That's the behaviour of the method. It returns after it finishes the entire download, and gives back the filename.

> client.download_media spawns a task

The official Telethon library does not. If you're using a wrapper or different library, I can't do anything about it.
