### ISSUE TITLE
Tokio 1.0 released

### ISSUE THREAD

**Issue by ForsakenHarmony** [Lonami/grammers#38]
https://tokio.rs/blog/2020-12-tokio-1-0

**Comment by Lonami** [comment]
[There were plans for this](https://t.me/gramme_rs/7261), but I didn't get around opening an issue, thanks! We probably want to do our best to keep all dependencies up to date as often as possible, not just tokio. If you would like to help, please be welcome.

**Comment by Lonami** [comment]
In the future, `cargo-outdated` and `serayuzgur.crates` in VS Code are our friends to find dependencies that could be updated.
