### ISSUE TITLE
Client handling updates twice per message after a delay

### ISSUE THREAD

**Issue by ThijmenMaus** [Lonami/grammers#46]
After running the demo code in [examples/echo.rs](https://github.com/Lonami/grammers/blob/master/lib/grammers-client/examples/echo.rs), the updates get received twice after a while.

### How to reproduce
1. Make a [new channel](https://imgur.com/a/EPOl5mP) under account A
2. Log in with account A's credentials in the `echo.rs` code
3. Add account B to the channel and make them admin
4. Make account B post a message
5. Run the program, so it waits for updates..

The code should react at first, responding with a message.

After a few minutes, the code runs again because it receives a new update, this should not happen..

**Comment by Lonami** [comment]
Conversation in the group: https://t.me/gramme_rs/7820 (read above).

**Comment by ThijmenMaus** [comment]
> Conversation in the group: https://t.me/gramme_rs/7820 (read above).

I know, that is me. I'm just making an issue to make it easier for you to handle :)
