### ISSUE TITLE
Handling of updates

### ISSUE THREAD

**Issue by Lonami** [Lonami/grammers#5]
How would we like to see updates being handled? Some options would be having a queue, and the user checks it using a stream-like interface:

```rust
while let Some(update) = client.wait_for_update()? {
    // user does whatever with the update
}
```

We could also follow Telethon's route and [manually register callbacks](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.updates.UpdateMethods.add_event_handler):
```rust
fn callback(event: events::NewMessage) {
    // user does whatever with the event
}
// ...

client.add_event_handler(callback);
```
Another option we could investigate is using some sort of [macros to act as "decorators"](https://t.me/rustdevs/21993):
```rust
[bot.NewMessage(pattern)]
fn message(event: events::NewMessage) {
    // user does whatever with the event
}
```

**Comment by swarnimarun** [comment]
Second and Third both make sense, but macros feel like they belong in a higher level crate.
For the very reason that adding high def macros would mean blowing up the dependencies.
At the very least we need proc-macro, syn, and qoute crates. If we want to write macros in sane fashion.

**Comment by Lonami** [comment]
Why does the first not make sense? There's a queue, the user reads from it as if it were a stream. It looks very reasonable to me.

**Comment by swarnimarun** [comment]
Because it will be blocking. Unless there is some way around  it...

**Comment by JuanPotato** [comment]
I mean that loop would block the current thread if it's not async, but there's no reason it needs to block the network. You can have a separate process running that takes in all responses from the network and sends the updates down the channel. Requests to be sent can be handled in that same loop. I'll explain the idea more in the async issue later

**Comment by Lonami** [comment]
The user would be free to run this in their own task/thread. The alternative (callbacks) is either a) the library handles the task/thread itself or b) there's a method that loops in the same thread and dispatches updates, but "blocks".

Most of the time, once you're done setting the application, you normally want to block on *something* regardless. The application needs to run for updates to keep arriving. So I don't think it's much of an issue.

**Comment by swarnimarun** [comment]
@JuanPotato I meant to block the thread, not the network. :P
It's 2020 almost nothing should block the network, heck we even have async io constructs in kernels such as io_uring.

**Comment by swarnimarun** [comment]
@Lonami That's likely how we should write the lower-level API. writing a higher-level API with blocking operations seems counter-intuitive.
Thinking from a JS/Python perspective.

**Comment by swarnimarun** [comment]
TBH I have been sploit by Lazy languages. (Blame Haskell lol)

**Comment by Streetwalrus** [comment]
IMHO, what the API should look like is more like this:

```rust
while let Some(packet) = poll_network(socket) {
    for update in grammers::iter_updates(packet) {
        do_something(update);
    }
}
```

In a threaded design you would just shove those events into a queue, and then a thread pool would pull from it and dispatch to user callbacks.
In an async design, you would spawn new tasks here (or pass those events back to an existing task waiting for them, if relevant).
You could even have a completely non-concurrent design if you wanted to.
This also allows the user to have multiple event sources in a single event loop, instead of having to e.g. spawn one thread per client just for the event loops, and it's also friendly towards other libraries.

Considering the above, I think callbacks are not a good solution for the low level API. They add friction for higher level layers to implement their own networking and concurrency model.

**Comment by Lonami** [comment]
What you suggest is a bit too low level for the `grammers-client`, which is supposed to already be the high-level abstraction. Something similar is already done lower down the abstraction layers, in the `grammers-mtsender`:

https://github.com/Lonami/grammers/blob/c8df43efa6acec26e4852f54c335ad775aa15cb9/lib/grammers-mtsender/src/lib.rs#L161-L170

Notice, this simple implementation has a loop which receives items from the network (your `poll_network`), and something that processes them (the MTProto, in your case, you have a very specific function for just some packets `iter_updates`).

**Comment by Lonami** [comment]
grammers might want a way to feed updates produced by requests back into the main updates, BUT with a flag to indicate "produced by yourself, you might not wanna trigger on this"

**Comment by Lonami** [comment]
Another thing is having a way to feed updates produced by requests back into the main updates, *but* embed a sort of flag to indicate "produced by yourself, you might not want to react to this".

**Comment by Lonami** [comment]
Regarding cache, it is very likely that the library should offer some form of caching, or else using updates will be extremely unergonomic. For user accounts, maybe we want to cache access hashes indefinitely (and entire entities only temporarily or under some settings). For bots, the access hash seems to actually not be needed, so this could be avoided, which is good because bots are likely to be used by a lot more people than a normal user will have active conversations.

Maybe the updates should contain the `pts` and all other necessary information and only refetch it if the user asks for it, since we don't know when they'll need it and when they won't ([Telegram says](https://core.telegram.org/api/updates) information should be refetched if updates are incomplete, but the user may have the data to complete it, so it's up to them to decide).

**Comment by Lonami** [comment]
I'm happy with the first approach of the OP (as finalized by https://github.com/Lonami/grammers/commit/34a68752f8eb82af8027608a37639fae97f2b06d; note that the tree at this commit deadlocks in a weird way but that's resolved in the later commit https://github.com/Lonami/grammers/commit/39528a084a81b889bb185ce3503005b216daed8d).

`next_update` will pop updates from an internal buffer (of configurable size, soon), and if there are none, it will `step` the network. Users are free to do things like `select!(next_updates, ctrl_c)`, as showcased in:

https://github.com/Lonami/grammers/blob/7761636347113d2fb791d6d097dd92b1c300da00/lib/grammers-client/examples/echo.rs#L74-L85

Users may even `step` on their own (or `invoke` stuff, which also calls `step`, and may put more updates in the buffer).

The structure described in [Tokio's blog - Inventing the Service trait](https://tokio.rs/blog/2021-05-14-inventing-the-service-trait) *may* be interesting, but in my opinion, that's better left for applications to do, not the client library itself.

If anyone wants to experiment with ideas such as that (or others), and can demonstrate that they're worth for the benefits they would provide (without cluttering too much grammers' code base, and it being something I can understand and maintain), please be welcome to leave another comment here / open another issue to discuss / send a pull request.
