### ISSUE TITLE
Extensive, beginner friendly documentation

### ISSUE THREAD

**Issue by Lonami** [Lonami/grammers#7]
Any product will be useless unless people know how to use it. Once we settle on a stable design, we should document every public module of (at least) the client library with instructions on how to get started, where to look, a section on using raw API and understanding the return types…

**Comment by swarnimarun** [comment]
I think we should refer to such documentations as a Cookbook or a Guide as in general how most other platforms do.
And not dilute the documentations too much.

It would certainly add a burden of maintaining such a Guide but I think keeping it separate from Documentations would cause a lot less pain and confusion to beginners, while allowing others to use Documentation without being annoyed by obnoxious amounts of explanation.

**Comment by Lonami** [comment]
It is definitely plausible to host a separate guide under https://gramme.rs, or even use [this project's wiki](https://github.com/Lonami/grammers/wiki) (which we can link as a guide from the main site or the documentation). So doing it like this instead of cluttering the reference (in https://docs.rs) is definitely a fair enough idea.

**Comment by swarnimarun** [comment]
In general starting with a simple Bot example would be good and also help with reaching to a MVP stage for the project.

Making general examples would also help us identify what needs to have better abstractions for implementation, like Client API is one which can obviously use a lot of work. Such examples would help identify the most important things to work on to make this project actually usable.

**Comment by Lonami** [comment]
There are already some under [`grammers-client/examples`](https://github.com/Lonami/grammers/tree/master/lib/grammers-client/examples). For the rest of libraries, examples within the documentation comments are probably enough, because they provide small building blocks. On contrary, the client is about integrating those to build something bigger.

**Comment by Lonami** [comment]
Good posts to keep in mind:
* [docs.rs now allows you to choose your build targets](https://blog.rust-lang.org/2020/03/15/docs-rs-opt-into-fewer-targets.html)
* [Guide on how to write documentation for a Rust crate](https://blog.guillaume-gomez.fr/articles/2020-03-12+Guide+on+how+to+write+documentation+for+a+Rust+crate)

**Comment by Lonami** [comment]
See also: `html_favicon_url` and `html_logo_url`, as explained in [What is rustdoc?](https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html).

**Comment by Lonami** [comment]
More on this: we probably want to run [`cargo-spellcheck`](https://github.com/drahnr/cargo-spellcheck/blob/master/README.md) to avoid typos.

**Comment by Lonami** [comment]
Closing for now. Still something I'd like to go over one day though.
