### ISSUE TITLE
Session files

### ISSUE THREAD

**Issue by Lonami** [Lonami/grammers#8]
How do we want to represent them, and how should we store them? Should they be mandatory to create a client instance? Would they have to be stored in files, or can we store them in databases? How do we make them share a common interface? What data should they store?

**Comment by swarnimarun** [comment]
I think we should start with discussing what a session is going to reflect in the context of this library, essentially, it's not clear to me if the session is supposed to just me some basic information and a Map of data, or is it supposed to be something more involved and intricate.

Answer what session is and what kinds of sessions we may have would likely important before deciding an implementation.

**Comment by Lonami** [comment]
A "session", at a minimum, must remember the following:
* Socket address of the user's datacenter.
* Authorization key bound to such datacenter.

It would be really helpful to also store:
* The `access_hash` of all seen `User` and `Channel`, because most methods need these.
* The update state, including `pts` and `date` (what [`updates.getDifference`](https://docs.rs/grammers-tl-types/0.1.0/grammers_tl_types/functions/updates/struct.GetDifference.html) needs, really).

It would also be a good idea to store the following:
* The identifier of the logged-in user, useful in many situations.
* A boolean to tell whether the currently logged-in user is a bot or not. This could be extended to all cached users.
* A boolean in the channels to tell whether they are groups or broadcasts.
* The identifier of the stored datacenters, and both IP versions (IPv4 and IPv6).
* Authorization keys for other datacenters (needed when e.g. downloading a file that is stored in a different datacenter than the user's).
* Cache usernames, so that users can use them without going through expensive remote calls.
* Cache seen files with chat and message identifier, so that if a download fails because the file reference expired, it can be retried.

**Comment by Lonami** [comment]
When implementing the client for a generic session type, perhaps the "complete login" part could be implemented for specific sessions, and not any generic one. This way it can call `FileSession::save` (this session-specific behaviour should be documented).

**Comment by Lonami** [comment]
Also, it might be a good idea to move the handling of updates PTS to `grammers-session`. This way the `grammers-client` could exclusively concern itself on being a nice abstraction over the RPC methods, and anything else is left to other libraries. So other people could even reuse the update handling without pulling the client.

**Comment by Lonami** [comment]
As of https://github.com/Lonami/grammers/commit/67f09912e1b8735e5a2202b5c17c8be6097240dd, I think I have decided:

* The session contains the minimum necessary (or which would otherwise be painful without).
  * Server address and corresponding authorization key for each datacenter.
  * The current user's ID, home DC, and whether they're a bot (only the home DC is mandatory, but the user ID and bot-ness is useful to know in several places, saving us a network request).
  * The current update state (this must persist for catching up on updates to work correctly). This includes the account-wide `pts` and a per-channel `pts` (also, the `qts`, `date` and `seq`).
* The serialization format doesn't matter much (currently, it's a few custom TL definitions because we get the generator for free). But the session must be able to be serialized into a bunch of bytes and back.
* There is a single `Session` type. Convenience methods to save or load, into or from memory or disk, are provided. Because there are no traits, we can easily add an `async fn` if we ever want to have, say, an `async` database storage.

Also, the session crate is responsible for dealing with proper update handling (in a non-`async` way, so that it can be reused) and probably caching of access hashes (an unfortunate requirement, because Telegram knows full well where an account has access to…).

Why not add more things to the session file:

* The small size allows it to be quickly saved and easily included anywhere (it could even be base64 encoded and included in an environment variable).
* Because dealing with access hashes should be fully transparent, and we shouldn't rely on "has my code seen this chat before, and was it saved successfully to cache?", I think it would do more harm than good. (If you lose your session for any reason, code that used to work may stop working; by forcing the code to deal with the no-hash situation properly from the beginning, this scenario is avoided).
  * Since chats (hash) are not stored in the session, it is also not stored whether they're a megagroup or a broadcast channel (for the very same reason). (Much like knowing whether the logged-in user is a bot or not, this is also useful, but still of less importance.)
  * The same applies to usernames, in that they are not stored. Work has been put into making it easy to encode chats into a compact, easy-to-embed form, so that usernames are not necessary. This is also more reliable, because usernames can change at any time, and cache invalidation is a hard problem.
* No need to store files. This is not our responsibility. It's the app's (like storing a reference to the users they care about). (This does not apply to storing the logged-in user ID or bot-ness, because this *is* needed to correctly handle updates).

If you have any thoughts on why this design is bad, please let me know, and we may reopen the issue to keep the discussion going.
