### ISSUE TITLE
"SetTypingRequest" Telethon equivalent in Gramme.rs

### ISSUE THREAD

**Issue by foodornt** [Lonami/grammers#95]
Is there any?

**Comment by Lonami** [comment]
I'll close this issue, as the raw API can be used and it's not too bad (it'll set the typing status for 5 seconds, if I remember correctly).

I wouldn't like the library to spawn tasks to periodically set the typing status for longer. And context expressions aren't really a thing. So maybe there's no much cleaner way than just calling set typing and having it enabled for 5 seconds.
